/* Allegro datafile object indexes, produced by grabber v3.9.32 (WIP), djgpp */
/* Datafile: d:\anwend\djgpp\allegro\tools\gf.dat */
/* Date: Wed Aug  9 13:30:28 2000 */
/* Do not hand edit! */

#define arial14                          0        /* FONT */
#define arial14m                         1        /* FONT */
#define base_cargo                       2        /* RLE  */
#define base_home                        3        /* RLE  */
#define base_lenemy                      4        /* RLE  */
#define base_senemy                      5        /* RLE  */
#define cargo1                           6        /* BMP  */
#define cargo_bigbombs1                  7        /* BMP  */
#define cargo_bigbombs3                  8        /* BMP  */
#define cargo_bombs10                    9        /* BMP  */
#define cargo_bombs20                    10       /* BMP  */
#define cargo_fuel                       11       /* BMP  */
#define cargo_life                       12       /* BMP  */
#define cargo_mgbullets                  13       /* BMP  */
#define cargo_mine1                      14       /* BMP  */
#define cargo_mine2                      15       /* BMP  */
#define cargo_mine3                      16       /* BMP  */
#define cargo_rockets                    17       /* BMP  */
#define cargo_shield                     18       /* BMP  */
#define debris_1_01                      19       /* BMP  */
#define debris_1_02                      20       /* BMP  */
#define debris_1_03                      21       /* BMP  */
#define debris_1_04                      22       /* BMP  */
#define debris_1_05                      23       /* BMP  */
#define debris_1_06                      24       /* BMP  */
#define debris_1_07                      25       /* BMP  */
#define debris_1_08                      26       /* BMP  */
#define debris_1_09                      27       /* BMP  */
#define debris_1_10                      28       /* BMP  */
#define debris_2_01                      29       /* BMP  */
#define debris_2_02                      30       /* BMP  */
#define debris_2_03                      31       /* BMP  */
#define debris_2_04                      32       /* BMP  */
#define debris_2_05                      33       /* BMP  */
#define debris_2_06                      34       /* BMP  */
#define debris_2_07                      35       /* BMP  */
#define debris_2_08                      36       /* BMP  */
#define debris_2_09                      37       /* BMP  */
#define debris_2_10                      38       /* BMP  */
#define debris_3_01                      39       /* BMP  */
#define debris_3_02                      40       /* BMP  */
#define debris_3_03                      41       /* BMP  */
#define debris_3_04                      42       /* BMP  */
#define debris_3_05                      43       /* BMP  */
#define debris_3_06                      44       /* BMP  */
#define debris_3_07                      45       /* BMP  */
#define debris_3_08                      46       /* BMP  */
#define debris_3_09                      47       /* BMP  */
#define debris_3_10                      48       /* BMP  */
#define debris_4_01                      49       /* BMP  */
#define debris_4_02                      50       /* BMP  */
#define debris_4_03                      51       /* BMP  */
#define debris_4_04                      52       /* BMP  */
#define debris_4_05                      53       /* BMP  */
#define debris_4_06                      54       /* BMP  */
#define debris_4_07                      55       /* BMP  */
#define debris_4_08                      56       /* BMP  */
#define debris_4_09                      57       /* BMP  */
#define debris_4_10                      58       /* BMP  */
#define debris_5_01                      59       /* BMP  */
#define debris_5_02                      60       /* BMP  */
#define debris_5_03                      61       /* BMP  */
#define debris_5_04                      62       /* BMP  */
#define debris_5_05                      63       /* BMP  */
#define debris_5_06                      64       /* BMP  */
#define debris_5_07                      65       /* BMP  */
#define debris_5_08                      66       /* BMP  */
#define debris_5_09                      67       /* BMP  */
#define debris_5_10                      68       /* BMP  */
#define effect_beam1_1                   69       /* RLE  */
#define effect_beam1_2                   70       /* RLE  */
#define effect_beam1_3                   71       /* RLE  */
#define effect_beam1_4                   72       /* RLE  */
#define effect_beam1_5                   73       /* RLE  */
#define effect_beam2_01                  74       /* RLE  */
#define effect_beam2_02                  75       /* RLE  */
#define effect_beam2_03                  76       /* RLE  */
#define effect_beam2_04                  77       /* RLE  */
#define effect_beam2_05                  78       /* RLE  */
#define effect_beam2_06                  79       /* RLE  */
#define effect_beam2_07                  80       /* RLE  */
#define effect_beam2_08                  81       /* RLE  */
#define effect_beam2_09                  82       /* RLE  */
#define effect_beam2_10                  83       /* RLE  */
#define effect_shield_1                  84       /* RLE  */
#define effect_shield_2                  85       /* RLE  */
#define effect_shield_3                  86       /* RLE  */
#define effect_tele2_01                  87       /* RLE  */
#define effect_tele2_02                  88       /* RLE  */
#define effect_tele2_03                  89       /* RLE  */
#define effect_tele2_04                  90       /* RLE  */
#define effect_tele2_05                  91       /* RLE  */
#define effect_tele2_06                  92       /* RLE  */
#define effect_tele2_07                  93       /* RLE  */
#define effect_tele2_08                  94       /* RLE  */
#define effect_tele2_09                  95       /* RLE  */
#define effect_tele2_10                  96       /* RLE  */
#define effect_tele_01                   97       /* RLE  */
#define effect_tele_02                   98       /* RLE  */
#define effect_tele_03                   99       /* RLE  */
#define effect_tele_04                   100      /* RLE  */
#define effect_tele_05                   101      /* RLE  */
#define effect_tele_06                   102      /* RLE  */
#define effect_tele_07                   103      /* RLE  */
#define effect_tele_08                   104      /* RLE  */
#define effect_tele_09                   105      /* RLE  */
#define effect_tele_10                   106      /* RLE  */
#define enemy_bigboss1_1                 107      /* RLE  */
#define enemy_bigboss1_2                 108      /* RLE  */
#define enemy_bigboss1_3                 109      /* RLE  */
#define enemy_bigboss1_4                 110      /* RLE  */
#define enemy_bigboss1_5                 111      /* RLE  */
#define enemy_n1_1                       112      /* RLE  */
#define enemy_n1_2                       113      /* RLE  */
#define enemy_n1_3                       114      /* RLE  */
#define enemy_n1_4                       115      /* RLE  */
#define enemy_n1_5                       116      /* RLE  */
#define enemy_s1_01                      117      /* RLE  */
#define enemy_s1_02                      118      /* RLE  */
#define enemy_s1_03                      119      /* RLE  */
#define enemy_s1_04                      120      /* RLE  */
#define enemy_s1_05                      121      /* RLE  */
#define enemy_s2_01                      122      /* RLE  */
#define enemy_s2_02                      123      /* RLE  */
#define enemy_s2_03                      124      /* RLE  */
#define enemy_s3_01                      125      /* RLE  */
#define enemy_s3_02                      126      /* RLE  */
#define enemy_s3_03                      127      /* RLE  */
#define enemy_s3_04                      128      /* RLE  */
#define enemy_s3_05                      129      /* RLE  */
#define enemy_s3_06                      130      /* RLE  */
#define enemy_s3_07                      131      /* RLE  */
#define enemy_s3_08                      132      /* RLE  */
#define enemy_s3_09                      133      /* RLE  */
#define enemy_s4_01                      134      /* RLE  */
#define enemy_s4_02                      135      /* RLE  */
#define enemy_s4_03                      136      /* RLE  */
#define enemy_s4_04                      137      /* RLE  */
#define enemy_s4_05                      138      /* RLE  */
#define enemy_s4_06                      139      /* RLE  */
#define enemy_s4_07                      140      /* RLE  */
#define enemy_s4_08                      141      /* RLE  */
#define enemy_s4_09                      142      /* RLE  */
#define enemy_s5_01                      143      /* RLE  */
#define enemy_s5_02                      144      /* RLE  */
#define enemy_s5_03                      145      /* RLE  */
#define enemy_s5_04                      146      /* RLE  */
#define enemy_s5_05                      147      /* RLE  */
#define enemy_s5_06                      148      /* RLE  */
#define enemy_s5_07                      149      /* RLE  */
#define enemy_s5_08                      150      /* RLE  */
#define expl_big2_01                     151      /* RLE  */
#define expl_big2_02                     152      /* RLE  */
#define expl_big2_03                     153      /* RLE  */
#define expl_big2_04                     154      /* RLE  */
#define expl_big2_05                     155      /* RLE  */
#define expl_big2_06                     156      /* RLE  */
#define expl_big2_07                     157      /* RLE  */
#define expl_big2_08                     158      /* RLE  */
#define expl_big2_09                     159      /* RLE  */
#define expl_big2_10                     160      /* RLE  */
#define expl_big2_11                     161      /* RLE  */
#define expl_big2_12                     162      /* RLE  */
#define expl_big2_13                     163      /* RLE  */
#define expl_big2_14                     164      /* RLE  */
#define expl_big_1                       165      /* RLE  */
#define expl_big_2                       166      /* RLE  */
#define expl_big_3                       167      /* RLE  */
#define expl_big_4                       168      /* RLE  */
#define expl_big_5                       169      /* RLE  */
#define expl_med1_01                     170      /* RLE  */
#define expl_med1_02                     171      /* RLE  */
#define expl_med1_03                     172      /* RLE  */
#define expl_med1_04                     173      /* RLE  */
#define expl_med1_05                     174      /* RLE  */
#define expl_med1_06                     175      /* RLE  */
#define expl_med1_07                     176      /* RLE  */
#define expl_sm1_01                      177      /* RLE  */
#define expl_sm1_02                      178      /* RLE  */
#define expl_sm1_03                      179      /* RLE  */
#define expl_sm1_04                      180      /* RLE  */
#define expl_sm1_05                      181      /* RLE  */
#define expl_sm1_06                      182      /* RLE  */
#define expl_sm1_07                      183      /* RLE  */
#define expl_sm1_08                      184      /* RLE  */
#define expl_sm1_09                      185      /* RLE  */
#define expl_sm1_10                      186      /* RLE  */
#define expl_sm2_01                      187      /* RLE  */
#define expl_sm2_02                      188      /* RLE  */
#define expl_sm2_03                      189      /* RLE  */
#define expl_sm2_04                      190      /* RLE  */
#define expl_sm2_05                      191      /* RLE  */
#define expl_sm2_06                      192      /* RLE  */
#define expl_sm2_07                      193      /* RLE  */
#define expl_sm3_01                      194      /* RLE  */
#define expl_sm3_02                      195      /* RLE  */
#define expl_sm3_03                      196      /* RLE  */
#define expl_sm3_04                      197      /* RLE  */
#define expl_sm3_05                      198      /* RLE  */
#define expl_sm_1                        199      /* RLE  */
#define gamepal                          200      /* PAL  */
#define impact10                         201      /* FONT */
#define impact10m                        202      /* FONT */
#define impact14                         203      /* FONT */
#define impact14m                        204      /* FONT */
#define obj_b_grav_1                     205      /* RLE  */
#define obj_b_grav_2                     206      /* RLE  */
#define obj_b_grav_3                     207      /* RLE  */
#define obj_building1_1                  208      /* RLE  */
#define obj_building2_1                  209      /* RLE  */
#define obj_building3_1                  210      /* RLE  */
#define obj_building4_1                  211      /* RLE  */
#define obj_building4_2                  212      /* RLE  */
#define obj_bumpd_1                      213      /* RLE  */
#define obj_bumpd_2                      214      /* RLE  */
#define obj_bumpd_3                      215      /* RLE  */
#define obj_bumpl_1                      216      /* RLE  */
#define obj_bumpl_2                      217      /* RLE  */
#define obj_bumpl_3                      218      /* RLE  */
#define obj_bumpr_1                      219      /* RLE  */
#define obj_bumpr_2                      220      /* RLE  */
#define obj_bumpr_3                      221      /* RLE  */
#define obj_bumpu_1                      222      /* RLE  */
#define obj_bumpu_2                      223      /* RLE  */
#define obj_bumpu_3                      224      /* RLE  */
#define obj_doorh2_1                     225      /* RLE  */
#define obj_doorh2_2                     226      /* RLE  */
#define obj_doorh2_3                     227      /* RLE  */
#define obj_doorh2_4                     228      /* RLE  */
#define obj_doorh_1                      229      /* RLE  */
#define obj_doorh_2                      230      /* RLE  */
#define obj_doorh_3                      231      /* RLE  */
#define obj_doorh_4                      232      /* RLE  */
#define obj_doorv2_1                     233      /* RLE  */
#define obj_doorv2_2                     234      /* RLE  */
#define obj_doorv2_3                     235      /* RLE  */
#define obj_doorv2_4                     236      /* RLE  */
#define obj_doorv_1                      237      /* RLE  */
#define obj_doorv_2                      238      /* RLE  */
#define obj_doorv_3                      239      /* RLE  */
#define obj_doorv_4                      240      /* RLE  */
#define obj_extra1_1                     241      /* RLE  */
#define obj_extra1_2                     242      /* RLE  */
#define obj_extra1_3                     243      /* RLE  */
#define obj_gstone_b1                    244      /* RLE  */
#define obj_gstone_s1                    245      /* RLE  */
#define obj_gstone_s2                    246      /* RLE  */
#define obj_gwalld_1                     247      /* RLE  */
#define obj_gwalld_2                     248      /* RLE  */
#define obj_gwalld_3                     249      /* RLE  */
#define obj_gwalld_4                     250      /* RLE  */
#define obj_gwalll_1                     251      /* RLE  */
#define obj_gwalll_2                     252      /* RLE  */
#define obj_gwalll_3                     253      /* RLE  */
#define obj_gwalll_4                     254      /* RLE  */
#define obj_gwallr_1                     255      /* RLE  */
#define obj_gwallr_2                     256      /* RLE  */
#define obj_gwallr_3                     257      /* RLE  */
#define obj_gwallr_4                     258      /* RLE  */
#define obj_gwallu_1                     259      /* RLE  */
#define obj_gwallu_2                     260      /* RLE  */
#define obj_gwallu_3                     261      /* RLE  */
#define obj_gwallu_4                     262      /* RLE  */
#define obj_man1_1                       263      /* RLE  */
#define obj_man1_2                       264      /* RLE  */
#define obj_man1_3                       265      /* RLE  */
#define obj_man1_4                       266      /* RLE  */
#define obj_pool1_1                      267      /* RLE  */
#define obj_pool1_2                      268      /* RLE  */
#define obj_pool1_3                      269      /* RLE  */
#define obj_pool2_1                      270      /* RLE  */
#define obj_pool2_2                      271      /* RLE  */
#define obj_pool2_3                      272      /* RLE  */
#define obj_ppile1                       273      /* RLE  */
#define obj_ppile2                       274      /* RLE  */
#define obj_rpoled_1                     275      /* RLE  */
#define obj_rpoled_2                     276      /* RLE  */
#define obj_rpoled_3                     277      /* RLE  */
#define obj_rpoled_4                     278      /* RLE  */
#define obj_rpoled_5                     279      /* RLE  */
#define obj_rpolel_1                     280      /* RLE  */
#define obj_rpolel_2                     281      /* RLE  */
#define obj_rpolel_3                     282      /* RLE  */
#define obj_rpolel_4                     283      /* RLE  */
#define obj_rpolel_5                     284      /* RLE  */
#define obj_rpoler_1                     285      /* RLE  */
#define obj_rpoler_2                     286      /* RLE  */
#define obj_rpoler_3                     287      /* RLE  */
#define obj_rpoler_4                     288      /* RLE  */
#define obj_rpoler_5                     289      /* RLE  */
#define obj_rpoleu_1                     290      /* RLE  */
#define obj_rpoleu_2                     291      /* RLE  */
#define obj_rpoleu_3                     292      /* RLE  */
#define obj_rpoleu_4                     293      /* RLE  */
#define obj_rpoleu_5                     294      /* RLE  */
#define obj_switchd_1                    295      /* RLE  */
#define obj_switchd_2                    296      /* RLE  */
#define obj_switchl_1                    297      /* RLE  */
#define obj_switchl_2                    298      /* RLE  */
#define obj_switchr_1                    299      /* RLE  */
#define obj_switchr_2                    300      /* RLE  */
#define obj_switchu_1                    301      /* RLE  */
#define obj_switchu_2                    302      /* RLE  */
#define obj_tree_1                       303      /* RLE  */
#define obj_tree_2                       304      /* RLE  */
#define obj_tunnel1_1                    305      /* RLE  */
#define obj_tunnel1_2                    306      /* RLE  */
#define obj_tunnel1_3                    307      /* RLE  */
#define obj_tunnel1_4                    308      /* RLE  */
#define obj_tunnel1_5                    309      /* RLE  */
#define panel                            310      /* FILE */

#define panel_cpl_2panel                 0        /* BMP  */
#define panel_cpl_lpanel                 1        /* BMP  */
#define panel_cpl_panel                  2        /* BMP  */
#define panel_pshield_1                  3        /* BMP  */
#define panel_pshield_2                  4        /* BMP  */
#define panel_pshield_3                  5        /* BMP  */
#define panel_shield_off                 6        /* BMP  */
#define panel_shield_on                  7        /* BMP  */
#define panel_shield_on1                 8        /* BMP  */
#define panel_shield_on2                 9        /* BMP  */
#define panel_shield_on3                 10       /* BMP  */
#define panel_shield_on4                 11       /* BMP  */
#define panel_shield_on5                 12       /* BMP  */
#define panel_statbar                    13       /* BMP  */
#define panel_weapon1_1                  14       /* BMP  */
#define panel_weapon1_2                  15       /* BMP  */
#define panel_weapon1_3                  16       /* BMP  */
#define panel_weapon1_pic                17       /* BMP  */
#define panel_weapon2_1                  18       /* BMP  */
#define panel_weapon2_2                  19       /* BMP  */
#define panel_weapon2_3                  20       /* BMP  */
#define panel_weapon2_pic                21       /* BMP  */
#define panel_weapon3_1                  22       /* BMP  */
#define panel_weapon3_2                  23       /* BMP  */
#define panel_weapon3_3                  24       /* BMP  */
#define panel_weapon3_pic                25       /* BMP  */
#define panel_weapon4_1                  26       /* BMP  */
#define panel_weapon4_2                  27       /* BMP  */
#define panel_weapon4_3                  28       /* BMP  */
#define panel_weapon4_pic                29       /* BMP  */
#define panel_weapon5_1                  30       /* BMP  */
#define panel_weapon5_2                  31       /* BMP  */
#define panel_weapon5_3                  32       /* BMP  */
#define panel_weapon5_pic                33       /* BMP  */
#define panel_weapon6_1                  34       /* BMP  */
#define panel_weapon6_2                  35       /* BMP  */
#define panel_weapon6_3                  36       /* BMP  */
#define panel_weapon6_pic                37       /* BMP  */
#define panel_weapon7_pic                38       /* BMP  */
#define panel_weapon8_pic                39       /* BMP  */
#define panel_weapon9_pic                40       /* BMP  */
#define panel_weapon_pic_empty           41       /* BMP  */
#define panel_COUNT                      42

#define pile1                            311      /* RLE  */
#define pile2                            312      /* RLE  */
#define plship1                          313      /* BMP  */
#define plship2                          314      /* BMP  */
#define plship2_1                        315      /* BMP  */
#define plship2_2                        316      /* BMP  */
#define plship3_1                        317      /* BMP  */
#define plship3_2                        318      /* BMP  */
#define plship4_1                        319      /* BMP  */
#define plship4_2                        320      /* BMP  */
#define plship5_1                        321      /* BMP  */
#define plship5_2                        322      /* BMP  */
#define shooter1_1                       323      /* RLE  */
#define shooter_down1                    324      /* RLE  */
#define shooter_down2                    325      /* RLE  */
#define shooter_down3                    326      /* RLE  */
#define shooter_left1                    327      /* RLE  */
#define shooter_left2                    328      /* RLE  */
#define shooter_left3                    329      /* RLE  */
#define shooter_pulse_1                  330      /* RLE  */
#define shooter_pulse_2                  331      /* RLE  */
#define shooter_pulse_3                  332      /* RLE  */
#define shooter_right1                   333      /* RLE  */
#define shooter_right2                   334      /* RLE  */
#define shooter_right3                   335      /* RLE  */
#define shooter_up1                      336      /* RLE  */
#define shooter_up2                      337      /* RLE  */
#define shooter_up3                      338      /* RLE  */
#define weapon_mine1_1                   339      /* BMP  */
#define weapon_mine1_2                   340      /* BMP  */
#define weapon_mine1e_1                  341      /* BMP  */
#define weapon_mine1e_2                  342      /* BMP  */
#define weapon_mine2_1                   343      /* BMP  */
#define weapon_mine2_2                   344      /* BMP  */
#define weapon_mine2e_1                  345      /* BMP  */
#define weapon_mine2e_2                  346      /* BMP  */
#define weapon_mine3_1                   347      /* BMP  */
#define weapon_mine3_2                   348      /* BMP  */
#define weapon_mine3e_1                  349      /* BMP  */
#define weapon_mine3e_2                  350      /* BMP  */

